dist: "xenial"
language: "python"

python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "pypy3.5-6.0"

install:
    - "pip install ."
    - "pip install -U black coveralls flake8 sphinx sphinx_rtd_theme"

script:
    - "coverage run --include='more_itertools/*.py' --omit='more_itertools/tests/*' setup.py test"
    - "black --check -t py35 -S -l 79 more_itertools/"
    - "flake8 ."
    - "sphinx-build -W -b html docs docs/_build/html"

notifications:
    - email: false

after_success:
    - "coveralls"
